site_name: Beauty Docs
site_url: https://github.com/linhpduc/beautydocs
nav:
  - Home: index.md
  - Framework Reference:
    - Overview: framework/index.md
    - Client cache: framework/client-cache.md
theme:
  name: material