site_name: Beauty Docs
site_url: https://github.com/linhpduc/beautydocs
nav:
  - Home: index.md
  - Framework Reference:
    - Overview: framework/index.md
    - Client cache: framework/client-cache.md
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
extra:
  version:
    provider: mike
    default: latest
extra_css:
  - stylesheets/extra.css